# Start with a base image containing Java runtime
FROM openjdk:11-jdk-alpine
# Add Maintainer Info
LABEL maintainer="sinduja.nasa01@gmail.com"
# Add a volume pointing to /tmp
VOLUME /tmp
# Make port 8081 available to the world outside this container
EXPOSE 8080
# The application's jar file
ARG JAR_FILE=target/demo3-0.0.1-SNAPSHOT.jar
# Add the application's jar to the container
ADD ${JAR_FILE} demo3-0.0.1-SNAPSHOT.jar
# Run the jar file
ENTRYPOINT ["java","-jar","/demo3-0.0.1-SNAPSHOT.jar"]